# Generated by Django 5.1.4 on 2024-12-25 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='local_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
