# Generated by Django 5.1.4 on 2025-01-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_local_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='content',
            field=models.CharField(blank=True, null=True),
        ),
    ]
